name: Android CI - android-asset-webshell (local-only assets)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Sanity check project tree
        run: |
          echo "== repo root =="
          ls -la
          echo "== android-asset-webshell =="
          ls -la android-asset-webshell || true
          echo "== gradlew presence =="
          ls -la android-asset-webshell/gradlew || (echo "ERROR: gradlew not found under android-asset-webshell. Please check in Gradle wrapper." && exit 1)

      - name: Enforce local-only assets (no remote fetch)
        working-directory: android-asset-webshell
        shell: bash
        run: |
          set -euo pipefail
          A=app/src/main/assets
          echo "Checking required local assets under: $A"
          test -f "$A/index.html"     || { echo "ERROR: $A/index.html missing"; exit 1; }
          test -f "$A/id-shim.js"     || { echo "ERROR: $A/id-shim.js missing"; exit 1; }
          test -f "$A/webjs.js"       || { echo "ERROR: $A/webjs.js missing"; exit 1; }
          test -f "$A/sw.js"          || { echo "ERROR: $A/sw.js missing"; exit 1; }
          echo "OK: all required assets present."
          echo "Show first lines of index.html:"
          sed -n '1,40p' "$A/index.html" || true

      - name: Build Debug
        working-directory: android-asset-webshell
        run: ./gradlew assembleDebug --stacktrace --info --no-daemon
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android-asset-webshell/app/build/outputs/apk/debug/*.apk

      - name: Build Release
        working-directory: android-asset-webshell
        run: ./gradlew assembleRelease --stacktrace --info --no-daemon
        env:
          JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android-asset-webshell/app/build/outputs/apk/release/*.apk
