name: Android CI - android-asset-webshell (local-only assets)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Sanity check project tree
        run: |
          echo "== repo root =="
          ls -la
          echo "== expect android-asset-webshell/ structure =="
          ls -la android-asset-webshell || { echo "ERROR: android-asset-webshell/ not found"; exit 1; }

      - name: Enforce local-only assets (no remote fetch)
        working-directory: android-asset-webshell
        shell: bash
        run: |
          set -euo pipefail
          A=app/src/main/assets
          echo "Checking required local assets under: $A"
          test -f "$A/index.html" || { echo "ERROR: $A/index.html missing"; exit 1; }
          test -f "$A/id-shim.js" || { echo "ERROR: $A/id-shim.js missing"; exit 1; }
          test -f "$A/webjs.js"   || { echo "ERROR: $A/webjs.js missing"; exit 1; }
          test -f "$A/sw.js"      || { echo "ERROR: $A/sw.js missing"; exit 1; }
          echo "OK: all required assets present."
          sed -n '1,40p' "$A/index.html" || true

      # 使用 gradle/gradle-build-action 直接指定 Gradle 版本，无需仓库内有 gradlew
      - name: Build Debug
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: android-asset-webshell
          gradle-version: 7.4.2
          arguments: assembleDebug --stacktrace --info --no-daemon

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: android-asset-webshell/app/build/outputs/apk/debug/*.apk

      - name: Build Release
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: android-asset-webshell
          gradle-version: 7.4.2
          arguments: assembleRelease --stacktrace --info --no-daemon

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: android-asset-webshell/app/build/outputs/apk/release/*.apk
